@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
header Brooks and MacDonald
title Cancel Item
actor server

participant "view :\n  ServerView" as view
participant "restaurant :\n  Restaurant " as restaurant
participant "order :\n OrderController" as controller
participant "order :\nOrder" as order

server -> view ++: Cancel Item
view -> controller ++: remove_item(cancelled_item)
controller -> order ++: remove_item()
order -> order : remove(item)
view -> restaurant ++: notify_view()
@enduml