@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

actor Cook
participant "view : KitchenView" as view
participant "restaurant"
participant "controller : KitchenController" as controller

participant "order : Order" as order
participant "item : OrderItem" as items

Cook -> view ++ : Mark As Served
view ->controller++: has_been_served(OrderItem)
controller -> order++: has_been_served(OrderItem)
order-> items++: has_been_served()
order -> order: remove(OrderItem)


view->restaurant++: notify_view()


@enduml