@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

actor Cook
participant "view : KitchenView" as view
participant "controller : KitchenController" as controller
participant "kc : KitchenController" as kc

participant "order : Order" as order
participant "item : OrderItem" as items

Cook -> view ++ : Mark As Served
view ->controller++: has_been_served(OrderItem)
controller -> order++: has_been_served(OrderItem)
order -> order: remove(OrderItem)
order-> items++: has_been_served()
order--
create kc
controller --> kc++: (view, restaurant, kitchen)

controller -->view++: set_controller(kc)
view->kc: create_ui()
kc->view++: create_kitchen_order_ui()







/'
For this one, all we need to do is have the order removed from the queue


'/


@enduml