@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
header Brooks and MacDonald
title Mark as Served
actor Cook
participant "view : \nKitchenView" as view
participant "restaurant"
participant "controller : \nKitchenController" as controller
participant "items : \nitem" as items

Cook -> view ++ : Presses button when item is served
view ->controller++: updater(order_item)
controller -> items++: mark_as_served()
items->items--: item.state="SERVED"
view->restaurant++: notify_view()
@enduml