@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

actor Cook
participant "view : \nKitchenView" as view
participant "restaurant"
participant "controller : \nKitchenController" as controller

participant "order : \nOrder" as order
participant "item : \nOrderItem" as items

Cook -> view ++ : Mark As Served
view ->controller++: has_been_served(OrderItem)
controller -> order++: has_been_served(OrderItem)
order-> items++: has_been_served()
order -> order: remove(OrderItem)


view->restaurant++: notify_view()


@enduml