@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
header Brooks and MacDonald
title Place Order

actor server

participant "Till :\n ServerView" as view
participant "restaurant :\n Restaurant " as restaurant
participant "order :\n OrderController" as controller
participant "tc :\n TableController" as tc
participant "order :\n Order" as order
participant "item :\n OrderItem" as item


server -> view ++: Place Order
view -> controller ++: update_order()
controller -> order ++: place_new_orders()

loop item in unordered_items()
    order-> item ++: mark_as_ordered()
end
create tc
controller --> tc ++: (view, restaurant, table)
controller -> view ++: set_controller(tc)
view->tc: create_ui()
tc->view++ :create_table_ui(table):
view -> restaurant ++: notify_view()

@enduml