@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
title Start Cooking
actor Cook
participant "view :\n KitchenView" as view
participant "restaurant :\n  Restaurant " as restaurant
participant "controller :\n KitchenController" as controller
participant "order :\nOrder" as order


Cook -> view ++: Start Cooking
view ->controller++: CookItem
controller->order --: Mark_As_Cooking()
view -> restaurant ++: notify_view()




@enduml